# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Research
    url: '/research/'
    weight: 30
  - name: Teaching
    url: '/teaching/'
    weight: 40
  - name: Others
    url: '/other-pubs/'
    weight: 50
  - name: CV
    url: media/Sijia_CV.pdf
    weight: 60
    params:
      target: _blank         # open in new tab
      rel: noopener  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.

